apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: iot-gateway
  namespace: iot-topology
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: iot-server-route
  namespace: iot-topology
spec:
  parentRefs:
  - name: iot-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: iot-server
      port: 8080